# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  run:
    desc: Run the application
    cmds:
      - go run ./cmd/app/main.go
      - defer: truncate -s0 debug.log
      - bat debug.log
