# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  run:
    desc: Run the application
    cmds:
      - truncate -s0 debug.log
      - truncate -s0 collector.log
      - go run ./cmd/app/main.go

  debug:
    desc: Builds and runs the app to be debugged
    cmds:
      - truncate -s0 debug.log
      - truncate -s0 collector.log
      - go build -gcflags="all=-N -l" -o otelly ./cmd/app/main.go
      - ./otelly
