receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"

exporters:
  otelly: {}

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otelly]
    traces:
      receivers: [otlp]
      exporters: [otelly]
